name: Native build

on:
  push:
    branches:
      - dev
    paths:
      - 'TMessagesProj/jni/**'
      - 'ss-rust/src/main/rust/**'
jobs:
  native:
    name: Native Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2
      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "ndk.dir=${ANDROID_HOME}/ndk/21.3.6528147" >> local.properties
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Native Cache
        uses: actions/cache@main
        with:
          path: |
            TMessagesProj/libs
            TMessagesProj/src/main/libs
          key: ${{ hashFiles('TMessagesProj/jni/**', 'ss-rust/src/main/rust/**') }}
      - name: Fix Gradle Memoery
        run: sed -i -e "s/16384/6144/g" gradle.properties
      - name: Native Build
        run: |
          test -f TMessagesProj/libs/libv2ray.aar && exit 0
          ./run init action
          ./run init libs
          ./run libs update